config/routes.rb
Rails.application.routes.draw do
  resources :tournaments do
    resources :results
    resources :entrants
    resources :results
    post 'entrants/update_all', to: 'entrants#update_all'
    post 'results/update_all', to: 'results#update_all'
  end
  resources :players
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :tournament
  belongs_to :entrant
  belongs_to :opponent, class_name: "Entrant"
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: %i[ show edit update destroy ]
  before_action :get_tournament

  # GET /results or /results.json
  def index
    @results = json_results(@tournament).to_json
  end

  # GET /results/1 or /results/1.json
  def show
  end

  # GET /results/new
  def new
    @result = @tournament.results.build
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results or /results.json
  def create
    @result = @tournament.results.build(result_params)

    respond_to do |format|
      if @result.save
        format.html { redirect_to new_tournament_result_path(@tournament), notice: "Result was successfully created." }
        format.json { render :show, status: :created, location: @result }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1 or /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to tournament_result_path(@tournament), notice: "Result was successfully updated." }
        format.json { render :show, status: :ok, location: @result }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1 or /results/1.json
  def destroy
    @result.destroy

    respond_to do |format|
      format.html { redirect_to results_url, notice: "Result was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def update_all
    tid = params["tournament_id"]
    Result.destroy_by(tournament_id: tid)
    new = params["_json"].filter {|e|
      !e["player1"].empty?
    }.map {|e| from_row(e)}
    if new.length > 0
      Result.insert_all(new)
    end
    respond_to do |format|
      format.json {
        results = json_results(@tournament)
        render json: results
      }
    end
  end

  private
    def get_tournament
      @tournament = Tournament.find(params[:tournament_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = @tournament.results.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def result_params
      params.require(:result).permit(:tournament_id, :division, :round, :entrant_id, :opponent_id, :score, :opponent_score, :first)
    end
    
    def from_row(e)
      keys = ["division", "round", "entrant_id", "opponent_id"]
      e.slice(*keys).merge({
        tournament_id: @tournament.id,
        score: e['score1'],
        opponent_score: e['score2'],
        first: e['first'] == 1
      })
    end

    def to_row(e)
     {
        "division" => e.division,
        "round" => e.round,
        "entrant_id" => e.entrant.id,
        "player1" => e.entrant.name,
        "score1" => e.score,
        "opponent_id" => e.opponent.id,
        "player2" => e.opponent.name,
        "score2" => e.opponent_score,
        "first" => e.first ? 1 : 2,
        "deleted" => false
      }
    end
 
    def json_results(tournament)
      tournament.results.map {|e| to_row(e)}
    end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_form.html.erb
<%= form_with(model: [@tournament, result]) do |form| %>
  <% if result.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
        <% result.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :division, style: "display: block" %>
    <%= form.text_field :division %>
    <%= form.label :round, style: "display: block" %>
    <%= form.text_field :round %>
  </div>

  <div>
    <%= form.label "Player", style: "display: block" %>
    <%= form.select :entrant_id, @tournament.entrants.collect {|e| [ e.name, e.id ]} %>
  </div>

  <div>
    <%= form.label "Opponent", style: "display: block" %>
    <%= form.select :opponent_id, @tournament.entrants.collect {|e| [ e.name, e.id ]} %>
  </div>

  <div>
    <%= form.label :score, style: "display: block" %>
    <%= form.number_field :score %>
  </div>

  <div>
    <%= form.label :opponent_score, style: "display: block" %>
    <%= form.number_field :opponent_score %>
  </div>

  <div>
    <%= form.label :first, style: "display: block" %>
    <%= form.check_box :first %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/results/_result.html.erb
<div id="<%= dom_id result %>">
  <p>
    <strong>Tournament:</strong>
    <%= result.tournament_id %>
  </p>

  <p>
    <strong>Division:</strong>
    <%= result.division %>
  </p>

  <p>
    <strong>Round:</strong>
    <%= result.round %>
  </p>

  <p>
    <strong>Entrant:</strong>
    <%= result.entrant_id %>
  </p>

  <p>
    <strong>Opponent:</strong>
    <%= result.opponent_id %>
  </p>

  <p>
    <strong>Score:</strong>
    <%= result.score %>
  </p>

  <p>
    <strong>Opponent score:</strong>
    <%= result.opponent_score %>
  </p>

  <p>
    <strong>First:</strong>
    <%= result.first %>
  </p>

</div>

app/views/results/edit.html.erb
<h1>Editing result</h1>

<%= render "form", result: @result %>

<br>

<div>
  <%= link_to "Show this result", @result %> |
  <%= link_to "Back to results", tournaments_results_path %>
</div>

app/views/results/index.html.erb
<h2><%= @tournament.name %> Results</h2>

<div data-controller="results"
     data-results-submit-url-value="/tournaments/<%= @tournament.id %>/results/update_all"
     data-results-rows-value="<%= @results %>"
>
  <revo-grid id="editgrid" data-results-target="grid" style="height:600px"></revo-grid>
  <div class="m-4">
    <button data-action="results#addRow"
            class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded">
      Add result
    </button>
    <button data-action="results#submit"
            class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded"
    >
      Save changes
    </button>
  </div>
</div>

<style>
.deleted {
  text-decoration: line-through;
  color: lightblue;
  background-color: darkgrey;
}
</style>

app/views/results/new.html.erb
<h1><%= @tournament.name %>: Enter result</h1>

<%= render "form", result: @result %>

<br>

<div>
  <%= link_to "Back to results", tournament_results_path %>
</div>

app/views/results/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @result %>

<div>
  <%= link_to "Edit this result", tournaments_edit_result_path(@result) %> |
  <%= link_to "Back to results", tournaments_results_path %>

  <%= button_to "Destroy this result", @result, method: :delete %>
</div>