config/routes.rb
Rails.application.routes.draw do
  resources :tournaments do
    resources :results
    resources :entrants
    resources :results
    post 'entrants/update_all', to: 'entrants#update_all'
    post 'results/update_all', to: 'results#update_all'
  end
  resources :players
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/entrant.rb
class Entrant < ApplicationRecord
  belongs_to :tournament
end

app/controllers/entrants_controller.rb
class EntrantsController < ApplicationController
  before_action :set_entrant, only: %i[ show edit update destroy ]
  before_action :get_tournament

  # GET /entrants or /entrants.json
  def index
    @entrants = json_entrants(@tournament).to_json
  end

  # GET /entrants/1 or /entrants/1.json
  def show
  end

  # GET /entrants/new
  def new
    @entrant = Entrant.new
  end

  # GET /entrants/1/edit
  def edit
  end

  # POST /entrants or /entrants.json
  def create
    @entrant = Entrant.new(entrant_params)

    respond_to do |format|
      if @entrant.save
        format.html { redirect_to entrant_url(@entrant), notice: "Entrant was successfully created." }
        format.json { render :show, status: :created, location: @entrant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entrant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entrants/1 or /entrants/1.json
  def update
    respond_to do |format|
      if @entrant.update(entrant_params)
        format.html { redirect_to entrant_url(@entrant), notice: "Entrant was successfully updated." }
        format.json { render :show, status: :ok, location: @entrant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entrant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entrants/1 or /entrants/1.json
  def destroy
    @entrant.destroy

    respond_to do |format|
      format.html { redirect_to entrants_url, notice: "Entrant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def update_all
    tid = params["tournament_id"]
    Entrant.destroy_by(tournament_id: tid)
    new = params["_json"].filter {|e|
      !e["name"].empty?
    }.map {|e|
      e.merge({"tournament_id": tid}).permit(:tournament_id, :userid, :name, :player_number, :rating, :division)
    }
    if new.length > 0
      Entrant.insert_all(new)
    end
    respond_to do |format|
      format.json {
        entrants = json_entrants(@tournament)
        render json: entrants
      }
    end
  end

  private
    def get_tournament
      @tournament = Tournament.find(params[:tournament_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_entrant
      @entrant = Entrant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entrant_params
      params.require(:entrant).permit(:tournament_id, :userid, :name, :player_number, :rating, :division)
    end

    def json_entrants(tournament)
      keys = ["division", "player_number", "userid", "name", "rating"]
      tournament.entrants.map {|e|
        e.as_json.slice(*keys).update("deleted": false)
      }
    end
end

app/helpers/entrants_helper.rb
module EntrantsHelper
end

app/views/entrants/_entrant.html.erb
<div id="<%= dom_id entrant %>">
  <p>
    <strong>Tournament:</strong>
    <%= entrant.tournament_id %>
  </p>

  <p>
    <strong>Userid:</strong>
    <%= entrant.userid %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= entrant.name %>
  </p>

  <p>
    <strong>Player number:</strong>
    <%= entrant.player_number %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= entrant.rating %>
  </p>

  <p>
    <strong>Division:</strong>
    <%= entrant.division %>
  </p>

</div>

app/views/entrants/_form.html.erb
<%= form_with(model: entrant) do |form| %>
  <% if entrant.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entrant.errors.count, "error") %> prohibited this entrant from being saved:</h2>

      <ul>
        <% entrant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :tournament_id, style: "display: block" %>
    <%= form.text_field :tournament_id %>
  </div>

  <div>
    <%= form.label :userid, style: "display: block" %>
    <%= form.text_field :userid %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :player_number, style: "display: block" %>
    <%= form.text_field :player_number %>
  </div>

  <div>
    <%= form.label :rating, style: "display: block" %>
    <%= form.number_field :rating %>
  </div>

  <div>
    <%= form.label :division, style: "display: block" %>
    <%= form.text_field :division %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/entrants/edit.html.erb
<h1>Editing entrant</h1>

<%= render "form", entrant: @entrant %>

<br>

<div>
  <%= link_to "Show this entrant", @entrant %> |
  <%= link_to "Back to entrants", entrants_path %>
</div>

app/views/entrants/grid.html.erb
<revo-grid data-controller="entrants" style="height: 400px" /> 

app/views/entrants/index.html.erb
<h2><%= @tournament.name %> Entrants</h2>

<div data-controller="entrants"
     data-entrants-submit-url-value="/tournaments/<%= @tournament.id %>/entrants/update_all"
     data-entrants-rows-value="<%= @entrants %>"
>
  <revo-grid id="editgrid" data-entrants-target="grid" style="height:600px"></revo-grid>
  <div class="m-4">
    <button data-action="entrants#addRow"
            class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded">
      Add entrant
    </button>
    <button data-action="entrants#submit"
            class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded"
    >
      Save changes
    </button>
  </div>
</div>

<style>
.deleted {
  text-decoration: line-through;
  color: lightblue;
  background-color: darkgrey;
}
</style>

app/views/entrants/new.html.erb
<h1>New entrant</h1>

<%= render "form", entrant: @entrant %>

<br>

<div>
  <%= link_to "Back to entrants", entrants_path %>
</div>

app/views/entrants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @entrant %>

<div>
  <%= link_to "Edit this entrant", edit_entrant_path(@entrant) %> |
  <%= link_to "Back to entrants", entrants_path %>

  <%= button_to "Destroy this entrant", @entrant, method: :delete %>
</div>